# Generated by Django 5.1.2 on 2024-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True)),
                ('course_fees', models.CharField(blank=True, max_length=200, null=True)),
                ('course_duration', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
