# Generated by Django 5.1.2 on 2024-12-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemaster',
            name='course_fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('payble_amount', models.FloatField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('fk_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.coursemaster')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(blank=True, null=True)),
                ('fk_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.studentmaster')),
            ],
        ),
    ]
