# Generated by Django 5.1.2 on 2024-12-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_alter_coursemaster_course_fees_studentmaster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaster',
            name='student_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
