# Generated by Django 5.1.2 on 2024-12-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0003_studentmaster_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmaster',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
