# Generated by Django 5.1.2 on 2024-12-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0005_adminmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('merchantuser_id', models.CharField(blank=True, max_length=200, null=True)),
                ('provider_referenceid', models.CharField(blank=True, max_length=1000, null=True)),
                ('checksum', models.CharField(blank=True, max_length=1000, null=True)),
                ('actual_amount', models.FloatField(blank=True, null=True)),
                ('plan_amount', models.FloatField(blank=True, null=True)),
                ('gst_amount', models.FloatField(blank=True, null=True)),
                ('payable_amount', models.FloatField(blank=True, null=True)),
                ('discount_amount', models.FloatField(default=0)),
                ('phonepe_status', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=200)),
                ('payment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.paymentmaster')),
            ],
        ),
    ]
