# Generated by Django 5.1.2 on 2024-12-15 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0006_subscriptiontable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontable',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptiontable',
            name='fk_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.studentmaster'),
        ),
    ]
