# Generated by Django 5.1.2 on 2024-12-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0007_alter_subscriptiontable_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontable',
            name='fk_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college_app.coursemaster'),
        ),
    ]
